server:
  port: 8761
eureka:
  instance:
    hostname: 10.10.181.166
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level: debug
management:
  security:
    enabled: false