server:
  port: 8761
security:
  basic:
    enabled: true #开启认证
  user:
    name: user
    password: 123qwe!@#
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level: debug